/* ============================================================================
 * Marketing Budget Dashboard - data file
 * ============================================================================
 *
 *  Source: "Marketing Expences August 2nd Week.xlsx", sheets Apr 26 to Aug 26.
 *  Every line item below was read straight from that workbook. Each month's
 *  extracted lines add up to that sheet's own Total row, and the five months
 *  add up to LKR 1,707,401.
 *
 *  Nothing here has been estimated, rounded or filled in. Where the workbook
 *  is inconsistent (see `note` on individual lines) the value is carried
 *  through exactly as recorded and flagged on screen rather than corrected.
 *
 *  To bring the dashboard up to date, add the new month's lines to `items`,
 *  add the month key to `recordedMonths`, and update `asOf`.
 * ========================================================================= */

var DASHBOARD_DATA = {

  meta: {
    currency: 'LKR',
    locale: 'en-LK',

    /* --- The one figure that did not come from the workbook ---------------
     * Supplied separately as the full marketing budget. Everything to do
     * with "remaining" and "percentage used" hangs off this number.
     * ------------------------------------------------------------------ */
    totalBudget: 6156000,

    budgetPeriodLabel: 'Financial year 2026/27 · April–March',
    asOf: '15 August 2026',

    /* --- Assumptions, stated so they can be corrected in one place -------
     * The budget was given as a single total with no split by month or by
     * category, so the dashboard cannot show a per-category budget and does
     * not invent one.
     *
     * `budgetIsPhased: false` means the pacing reference on this page is an
     * even spread of the total across `periodMonths` — LKR 513,000 a month.
     * That is an assumption, not an approved plan, and it is labelled as one
     * wherever it appears. If you have a real monthly phasing, put it in
     * `monthlyBudget` below and set `budgetIsPhased: true`.
     * ------------------------------------------------------------------ */
    periodMonths: 12,
    monthsElapsed: 4.5,          // April to July complete, plus half of August
    budgetIsPhased: false,
    monthlyBudget: null,         // e.g. { Apr: 500000, May: 450000, ... }

    /* The workbook's sheet titles say 2026 but most date cells carry 2025,
     * and several dates read as month/day where the rest of the file is
     * day/month. Amounts are grouped by the sheet they appear on, which is
     * unambiguous; the date column is shown exactly as recorded and queried
     * rows are flagged. Set to false once the workbook has been tidied. */
    showDateQueries: true
  },

  /* Category order fixes the colour each one wears, so a category keeps
     its colour no matter how the figures move. "Other" is deliberately
     grey rather than a categorical hue. */
  categories: [
    { key: 'web',         name: 'Website development'        },
    { key: 'digital',     name: 'Digital advertising'        },
    { key: 'sponsor',     name: 'Sponsorships'               },
    { key: 'subs',        name: 'Subscriptions & listings'   },
    { key: 'events',      name: 'Events'                     },
    { key: 'collateral',  name: 'Print & collateral'         },
    { key: 'seasonal',    name: 'Seasonal campaigns'         },
    { key: 'other',       name: 'Other'                      },
  ],

  /* The full budget period. `recorded: true` marks months whose spend has
     actually been entered; the rest are still to come. */
  months: [
    { key: 'Apr',   name: 'April 2026',          recorded: true,  },
    { key: 'May',   name: 'May 2026',            recorded: true,  },
    { key: 'Jun',   name: 'June 2026',           recorded: true,  },
    { key: 'Jul',   name: 'July 2026',           recorded: true,  },
    { key: 'Aug',   name: 'August 2026',         recorded: true,  },
    { key: 'Sep',   name: 'September 2026',      recorded: false, },
    { key: 'Oct',   name: 'October 2026',        recorded: false, },
    { key: 'Nov',   name: 'November 2026',       recorded: false, },
    { key: 'Dec',   name: 'December 2026',       recorded: false, },
    { key: 'Jan',   name: 'January 2027',        recorded: false, },
    { key: 'Feb',   name: 'February 2027',       recorded: false, },
    { key: 'Mar',   name: 'March 2027',          recorded: false, },
  ],

  /* August 2026 is a part month — the workbook runs to the second week. */
  partialMonth: 'Aug',

  /* Every line item in the workbook, in sheet order. */
  items: [
    { month: 'Apr', date: '04/06/2025', cat: 'collateral',
      item: 'Photo Frame',
      desc: 'New Photo Frame for Quality Policy',
      amount: 1200, pay: 'Cash',
      note: 'recorded as 04/06/2025, in the April sheet' },
    { month: 'Apr', date: '04/06/2025', cat: 'events',
      item: 'Cakes and Patty',
      desc: 'for the WTA Vote launch event 60 Patties, 2 4lb Cakes',
      amount: 32600, pay: 'Cash',
      note: 'recorded as 04/06/2025, in the April sheet' },
    { month: 'Apr', date: '21/4/2025', cat: 'digital',
      item: 'FB Ads',
      desc: 'World Travel Awards Vote Ad',
      amount: 30210, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'Apr', date: '21/4/2025', cat: 'digital',
      item: 'IG Boosts',
      desc: 'World Travel Awards Vote Ad',
      amount: 16280, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'Apr', date: '25/4/2025', cat: 'digital',
      item: 'IG Boosts',
      desc: 'World Travel Awards Vote Ad',
      amount: 4886, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'Apr', date: '27/4/2025', cat: 'digital',
      item: 'IG Boosts',
      desc: 'World Travel Awards Vote Ad',
      amount: 4886, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'Apr', date: '27/4/2025', cat: 'digital',
      item: 'FB Ads',
      desc: 'World Travel Awards Vote Ad',
      amount: 30210, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'Apr', date: '28/4/2025', cat: 'digital',
      item: 'IG Boosts',
      desc: 'World Travel Awards Vote Ad',
      amount: 4886, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'Apr', date: '28/4/2025', cat: 'digital',
      item: 'IG Boosts',
      desc: 'World Travel Awards Vote Ad',
      amount: 4886, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'Apr', date: '29/4/2025', cat: 'digital',
      item: 'IG Boosts',
      desc: 'World Travel Awards Vote Ad',
      amount: 10577, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'Apr', date: '29/4/2025', cat: 'digital',
      item: 'IG Boosts',
      desc: 'World Travel Awards Vote Ad',
      amount: 10577, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'Apr', date: '30/4/2025', cat: 'digital',
      item: 'FB Ads',
      desc: 'World Travel Awards Vote Ad',
      amount: 22408, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'May', date: '05/04/2025', cat: 'digital',
      item: 'FB Ads',
      desc: 'World Travel Awards Vote Ad',
      amount: 30210, pay: 'Chami\'s Card',
      note: 'recorded as 05/04/2025, in the May sheet' },
    { month: 'May', date: '05/04/2025', cat: 'digital',
      item: 'IG Boosts',
      desc: 'World Travel Awards Vote Ad',
      amount: 16146, pay: 'Chami\'s Card',
      note: 'recorded as 05/04/2025, in the May sheet' },
    { month: 'May', date: '05/06/2025', cat: 'subs',
      item: 'Survey monkey',
      desc: 'Yearly Subscription payment',
      amount: 128520, pay: 'Chami\'s Card',
      note: 'recorded as 05/06/2025, in the May sheet' },
    { month: 'May', date: '05/06/2025', cat: 'collateral',
      item: 'Baggage tags',
      desc: 'Baggage tags (1000)',
      amount: 47540, pay: 'Chami\'s Card',
      note: 'recorded as 05/06/2025, in the May sheet' },
    { month: 'May', date: '05/07/2025', cat: 'seasonal',
      item: 'Sticky notes for mothers day video',
      desc: '',
      amount: 550, pay: 'Cash',
      note: 'recorded as 05/07/2025, in the May sheet' },
    { month: 'May', date: '05/08/2025', cat: 'digital',
      item: 'IG Boosts',
      desc: 'World Travel Awards Vote Ad',
      amount: 16146, pay: 'Chami\'s Card',
      note: 'recorded as 05/08/2025, in the May sheet' },
    { month: 'May', date: '05/10/2025', cat: 'digital',
      item: 'FB Ads',
      desc: 'World Travel Awards Vote Ad',
      amount: 30210, pay: 'Chami\'s Card',
      note: 'recorded as 05/10/2025, in the May sheet' },
    { month: 'May', date: '05/12/2025', cat: 'digital',
      item: 'IG Boosts',
      desc: 'World Travel Awards Vote Ad',
      amount: 16146, pay: 'Chami\'s Card',
      note: 'recorded as 05/12/2025, in the May sheet' },
    { month: 'May', date: '16/5/2025', cat: 'digital',
      item: 'IG Boosts',
      desc: 'WTA and SATA Vote Ads',
      amount: 16146, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'May', date: '20/5/2025', cat: 'digital',
      item: 'FB Ads',
      desc: 'WTA and SATA Vote Ads',
      amount: 30210, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'May', date: '20/5/2025', cat: 'digital',
      item: 'IG Boosts',
      desc: 'WTA and SATA Vote Ads',
      amount: 16146, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'May', date: '21/5/2025', cat: 'digital',
      item: 'IG Boosts',
      desc: 'WTA and SATA Vote Ads',
      amount: 3607, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'May', date: '23/5/2025', cat: 'digital',
      item: 'IG Boosts',
      desc: 'WTA and SATA Vote Ads',
      amount: 16146, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'May', date: '25/5/2025', cat: 'digital',
      item: 'FB Ads',
      desc: 'WTA and SATA Vote Ads',
      amount: 30210, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'May', date: '31/5/2025', cat: 'digital',
      item: 'FB Ads',
      desc: 'WTA and SATA Vote Ads',
      amount: 19991, pay: 'Chami\'s Card',
      note: 'year recorded as 2025' },
    { month: 'Jun', date: '06/12/2025', cat: 'collateral',
      item: 'Baggage Tags',
      desc: 'Bagggae Tags from Lake House Printers',
      amount: 5600, pay: '—',
      note: 'recorded as 06/12/2025, in the June sheet' },
    { month: 'Jun', date: '22/6/2025', cat: 'seasonal',
      item: 'Fathers Day',
      desc: 'Fathers day Gifts (Apples chocolates and others)',
      amount: 18484, pay: '—',
      note: 'year recorded as 2025' },
    { month: 'Jun', date: '22/6/2025', cat: 'seasonal',
      item: 'Fathers Day',
      desc: 'Farther day gift boxes and stickers',
      amount: 4750, pay: '—',
      note: 'year recorded as 2025' },
    { month: 'Jun', date: '22/6/2025', cat: 'seasonal',
      item: 'Fathers Day',
      desc: 'Father\'s Day Gift-20 Peanut Packets',
      amount: 7305, pay: '—',
      note: 'year recorded as 2025' },
    { month: 'Jun', date: '22/6/2025', cat: 'seasonal',
      item: 'Fathers Day',
      desc: 'Transport expences - Fathers Day',
      amount: 2933, pay: '—',
      note: 'year recorded as 2025' },
    { month: 'Jun', date: '22/6/2025', cat: 'seasonal',
      item: 'Fathers Day',
      desc: 'Gift Boxes for Father\'s Day',
      amount: 3250, pay: '—',
      note: 'year recorded as 2025' },
    { month: 'Jun', date: '24/6/2025', cat: 'collateral',
      item: 'Business Cards',
      desc: 'business cards - Nilmini - 100',
      amount: 2375, pay: '—',
      note: 'year recorded as 2025' },
    { month: 'Jun', date: '25/6/2025', cat: 'collateral',
      item: 'Business Cards',
      desc: 'business cards - Asitha - 100',
      amount: 2375, pay: '—',
      note: 'year recorded as 2025' },
    { month: 'Jun', date: '30/6/2025', cat: 'other',
      item: 'Newspaper payment',
      desc: 'Newspaper payment - June',
      amount: 1900, pay: '—',
      note: 'year recorded as 2025' },
    { month: 'Jul', date: '07/01/2025', cat: 'subs',
      item: 'Promise.lk',
      desc: 'Government procurement website Excisting client CEB requested us to register',
      amount: 5000, pay: 'Fiona\'s Card',
      note: 'recorded as 07/01/2025, in the July sheet' },
    { month: 'Jul', date: '07/10/2025', cat: 'web',
      item: 'Website advanced payment',
      desc: 'Phase 2 advanced payment',
      amount: 700000, pay: 'Bank Transfer',
      note: 'recorded as 07/10/2025, in the July sheet' },
    { month: 'Jul', date: '16/7/2025', cat: 'collateral',
      item: 'Banner',
      desc: 'ATL Logo Banner',
      amount: 2250, pay: 'Cash',
      note: 'year recorded as 2025' },
    { month: 'Jul', date: '17/7/2025', cat: 'collateral',
      item: 'Business Cards',
      desc: 'Business Cards for Bala',
      amount: 1500, pay: 'Cash',
      note: 'year recorded as 2025' },
    { month: 'Jul', date: '20/7/2025', cat: 'events',
      item: 'Union Bank Pensioners Event',
      desc: 'Expences for Union Bank Pensioners Event',
      amount: 58325, pay: 'Cash',
      note: 'year recorded as 2025' },
    { month: 'Jul', date: '20/7/2026', cat: 'events',
      item: 'Flyers and Vouchers',
      desc: 'For Union Bank Pensioners Event',
      amount: 22504, pay: 'Cash' },
    { month: 'Jul', date: '24/7/2026', cat: 'collateral',
      item: 'Ticket Cover Samples',
      desc: 'Anim8',
      amount: 1500, pay: 'Cash' },
    { month: 'Jul', date: '24/7/2026', cat: 'collateral',
      item: 'Ticket Cover Samples',
      desc: 'Lakehouse',
      amount: 345, pay: 'Cash' },
    { month: 'Jul', date: '28/7/2026', cat: 'sponsor',
      item: 'Sponsorship',
      desc: 'Sponsorship payment for secraterial conference',
      amount: 250000, pay: 'Bank Transfer' },
    { month: 'Jul', date: '30/7/2026', cat: 'subs',
      item: 'SLT Listing',
      desc: 'Payment for SLT rainbowpages online listing',
      amount: 17700, pay: 'Cash' },
    { month: 'Aug', date: '08/06/2026', cat: 'collateral',
      item: 'Ticket Cover Samples',
      desc: 'Anim8 (matte print)',
      amount: 1500, pay: 'Cash',
      note: 'recorded as 08/06/2026, in the August sheet' },
    { month: 'Aug', date: '08/06/2026', cat: 'collateral',
      item: 'Visa stickers',
      desc: 'Visa stickers',
      amount: 3900, pay: 'Cash',
      note: 'recorded as 08/06/2026, in the August sheet' },
    { month: 'Aug', date: '08/11/2026', cat: 'collateral',
      item: 'Business Cards',
      desc: 'for Rochely - (Promotion)',
      amount: 2375, pay: 'Cash',
      note: 'recorded as 08/11/2026, in the August sheet' },
  ]
};
